import { Download, Eye } from 'lucide-react';
import { useState } from 'react';
import { EmptyState } from '@/components/app/empty-state';
import {
    formatBytes,
    relativeTime,
} from '@/components/data-processing/job-utils';
import { fileIcon } from '@/components/file/file-utils';
import { FilePreviewDialog } from '@/components/file/file-preview-dialog';
import { Button } from '@/components/ui/button';
import { useTranslation } from '@/hooks/use-translation';
import type { DataProcessingJob, JobArtifact } from '@/types';

type Props = {
    run: DataProcessingJob;
};

/**
 * PIPE-06 — artifact list: file icon, size, expiry, download and a preview for
 * previewable types. Expired artifacts keep their metadata but lose download.
 */
export function RunArtifacts({ run }: Props) {
    const { t } = useTranslation();
    const [preview, setPreview] = useState<JobArtifact | null>(null);

    if (run.artifacts.length === 0) {
        return (
            <EmptyState
                variant="compact"
                title={t('No files were generated by this run.')}
            />
        );
    }

    return (
        <div className="space-y-2">
            <ul className="space-y-2">
                {run.artifacts.map((artifact) => {
                    const Icon = fileIcon(artifact.mime_type);
                    const expired =
                        artifact.expires_at !== null &&
                        new Date(artifact.expires_at) < new Date();

                    return (
                        <li
                            key={artifact.key}
                            className="flex items-center gap-3 rounded-lg border p-3"
                        >
                            <span className="flex size-9 shrink-0 items-center justify-center rounded-md bg-muted">
                                <Icon className="size-4 text-muted-foreground" />
                            </span>

                            <div className="min-w-0 flex-1">
                                <p className="truncate text-sm font-medium">
                                    {artifact.file_name ?? artifact.label}
                                </p>
                                <p className="text-xs text-muted-foreground">
                                    {formatBytes(artifact.size)}
                                    {artifact.expires_at && (
                                        <>
                                            {' · '}
                                            {expired
                                                ? t('Expired')
                                                : t('Expires :time', {
                                                      time: relativeTime(
                                                          artifact.expires_at,
                                                      ),
                                                  })}
                                        </>
                                    )}
                                </p>
                            </div>

                            <div className="flex shrink-0 gap-2">
                                {artifact.mime_type && (
                                    <Button
                                        type="button"
                                        variant="ghost"
                                        size="sm"
                                        onClick={() => setPreview(artifact)}
                                    >
                                        <Eye className="size-4" />
                                        {t('Preview')}
                                    </Button>
                                )}

                                {artifact.downloadable &&
                                    artifact.download_url && (
                                        <Button
                                            asChild
                                            variant="outline"
                                            size="sm"
                                        >
                                            <a href={artifact.download_url}>
                                                <Download className="size-4" />
                                                {t('Download')}
                                            </a>
                                        </Button>
                                    )}
                            </div>
                        </li>
                    );
                })}
            </ul>

            <FilePreviewDialog
                file={
                    preview
                        ? {
                              name: preview.file_name ?? preview.label,
                              mime_type: preview.mime_type,
                              url: preview.download_url ?? null,
                              size: preview.size,
                          }
                        : null
                }
                open={preview !== null}
                onOpenChange={(open) => !open && setPreview(null)}
            />
        </div>
    );
}
